### ISSUE TITLE
Test and migrate Docker registry example to 1.9.

### ISSUE THREAD

**Issue by joerg84** [dcos/examples#74]

**Comment by indcoder** [comment]
I'll take a stab at this.

**Comment by pleia2** [comment]
Thanks for taking this example on, Augustine!

I've noticed there hasn't been a pull request submitted yet, do you need any help, or just need some more time? If you ran into a problem, updating this issue to explain would be a huge help so we can try to assist you.

If something came up and you aren't able to complete updating this example, no problem! Just let us know that so we can assign it to another community member. We'll look forward to working with you next time :)

**Comment by indcoder** [comment]
Hi @pleia2 . I did take it for a spin but got stuck in the first few lines. Since I was testing this on both AWS and Azure, there is an action  at the start on creating a self signed certificate in the **bootstrap** node. But no such node is created on the Azure or AWS deploy. Before I had a chance to apply any thought, got caught up in greenkeeper whack-a-mole with my other OSS projects that I maintain.

**Comment by pleia2** [comment]
Thanks for this update, do you think you'll be able to take a look at this a bit closer anytime soon, or should we ask someone else to take over? Either way, thanks for giving it a try! :smiley:

**Comment by pleia2** [comment]
Digging into this one, it is indeed a very complex example, a WIP PR is up at #185

**Comment by fernandosanchezmunoz** [comment]
PR here https://github.com/dcos/examples/pull/186
@pleia2 @ryadav88
